use time::OffsetDateTime;
use uuid::Uuid;

use crate::{StorageBackend, StorageByteStream, StorageNamespace};

/// Request body for storing a new object.
#[derive(Clone, Debug)]
pub struct StoragePutRequest {
    /// Logical namespace for the generated storage key.
    pub namespace: StorageNamespace,
    /// Original filename retained as metadata only.
    pub file_name: Option<String>,
    /// Caller-provided MIME type metadata.
    pub mime_type: Option<String>,
    /// Full object bytes to store.
    pub bytes: Vec<u8>,
}

/// Streaming request body for storing a new object.
#[derive(Debug)]
pub struct StoragePutStreamRequest {
    /// Logical namespace for the generated storage key.
    pub namespace: StorageNamespace,
    /// Original filename retained as metadata only.
    pub file_name: Option<String>,
    /// Caller-provided MIME type metadata.
    pub mime_type: Option<String>,
    /// Streaming object bytes to store.
    pub body: StorageByteStream,
}

/// Provider-neutral metadata describing a stored object.
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct StoredObject {
    /// Stable object identifier generated by [`crate::StorageService`].
    pub object_id: Uuid,
    /// Logical namespace used in the object key.
    pub namespace: StorageNamespace,
    /// Provider that stores the object bytes.
    pub backend: StorageBackend,
    /// Provider-neutral storage key.
    pub storage_key: String,
    /// Original filename retained as metadata only.
    pub original_file_name: Option<String>,
    /// Caller-provided MIME type metadata.
    pub mime_type: Option<String>,
    /// Object size in bytes.
    pub size_bytes: u64,
    /// Lowercase hexadecimal SHA-256 checksum.
    pub sha256_hex: String,
    /// UTC creation timestamp assigned by the storage service.
    pub created_at: OffsetDateTime,
}

/// Object metadata plus loaded bytes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StorageObjectBody {
    /// Stored object metadata.
    pub object: StoredObject,
    /// Loaded object bytes.
    pub bytes: Vec<u8>,
}

/// Object metadata plus streaming bytes.
#[derive(Debug)]
pub struct StorageObjectStream {
    /// Stored object metadata.
    pub object: StoredObject,
    /// Streaming object bytes.
    pub body: StorageByteStream,
}
